version: '3.3'

services:
  web:
    external_links:
      - core_db
    container_name: ${PROJECTNAME}_dev
    environment:
      VIRTUAL_HOST: ${PROJECTNAME}.local
      LETSENCRYPT_HOST: ${PROJECTNAME}.local

networks:
    default:
      external:
        name: corenetwork
